version: '3.4'

services:
  onlinecourse.courseprogram.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  onlinecourse.courseprogram.ocelotapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

